In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [4]:
df=pd.read_csv("/content/drive/MyDrive/Datasets/covid_toy.csv")

In [5]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [9]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=["has_covid"]),df["has_covid"],test_size=0.2)

In [15]:
X_train

age  gender  fever   cough       city
67   65    Male   99.0    Mild  Bangalore
94   79    Male    NaN  Strong    Kolkata
39   50  Female  103.0    Mild    Kolkata
44   20    Male  102.0  Strong      Delhi
82   24    Male   98.0    Mild    Kolkata
..  ...     ...    ...     ...        ...
68   54  Female  104.0  Strong    Kolkata
37   55    Male  100.0    Mild    Kolkata
0    60    Male  103.0    Mild    Kolkata
84   69  Female   98.0  Strong     Mumbai
20   12    Male   98.0  Strong  Bangalore

[80 rows x 5 columns]

In [16]:
X_test

age  gender  fever   cough       city
60   24  Female  102.0  Strong  Bangalore
63   10    Male  100.0    Mild  Bangalore
11   65  Female   98.0    Mild     Mumbai
22   71  Female   98.0  Strong    Kolkata
73   34    Male   98.0  Strong    Kolkata
12   25  Female   99.0  Strong    Kolkata
33   26  Female   98.0    Mild    Kolkata
4    65  Female  101.0    Mild     Mumbai
57   49  Female   99.0  Strong  Bangalore
45   72    Male   99.0    Mild  Bangalore
14   51    Male  104.0    Mild  Bangalore
89   46    Male  103.0  Strong  Bangalore
46   19  Female  101.0    Mild     Mumbai
15   70    Male  103.0  Strong    Kolkata
85   16  Female  103.0    Mild  Bangalore
58   23    Male   98.0  Strong     Mumbai
53   83    Male   98.0    Mild      Delhi
5    84  Female    NaN    Mild  Bangalore
69   73  Female  103.0    Mild      Delhi
59    6  Female  104.0    Mild    Kolkata

# 1. Without using Column Transformer

In [35]:
si=SimpleImputer()
X_train_fever=si.fit_transform(X_train[["fever"]])
X_test_fever=si.fit_transform(X_test[["fever"]])
X_train_fever.shape
#NaN value is filled now with X_test mean

(80, 1)

In [36]:
X_train_fever

array([[ 99.        ],
       [100.94366197],
       [103.        ],
       [102.        ],
       [ 98.        ],
       [ 99.        ],
       [100.        ],
       [100.94366197],
       [104.        ],
       [101.        ],
       [101.        ],
       [101.        ],
       [103.        ],
       [101.        ],
       [ 99.        ],
       [104.        ],
       [104.        ],
       [100.94366197],
       [ 98.        ],
       [100.        ],
       [104.        ],
       [102.        ],
       [101.        ],
       [104.        ],
       [102.        ],
       [ 99.        ],
       [100.94366197],
       [102.        ],
       [100.94366197],
       [100.        ],
       [102.        ],
       [ 99.        ],
       [ 98.        ],
       [101.        ],
       [ 99.        ],
       [100.        ],
       [100.        ],
       [100.        ],
       [ 98.        ],
       [ 98.        ],
       [102.        ],
       [104.        ],
       [102.        ],
       [101

In [37]:
X_test.describe()

age       fever
count  20.000000   19.000000
mean   45.600000  100.473684
std    25.848547    2.318247
min     6.000000   98.000000
25%    23.750000   98.000000
50%    47.500000  100.000000
75%    70.250000  103.000000
max    84.000000  104.000000

In [29]:
X_train_fever

array([[ 99.        ],
       [100.94366197],
       [103.        ],
       [102.        ],
       [ 98.        ],
       [ 99.        ],
       [100.        ],
       [100.94366197],
       [104.        ],
       [101.        ],
       [101.        ],
       [101.        ],
       [103.        ],
       [101.        ],
       [ 99.        ],
       [104.        ],
       [104.        ],
       [100.94366197],
       [ 98.        ],
       [100.        ],
       [104.        ],
       [102.        ],
       [101.        ],
       [104.        ],
       [102.        ],
       [ 99.        ],
       [100.94366197],
       [102.        ],
       [100.94366197],
       [100.        ],
       [102.        ],
       [ 99.        ],
       [ 98.        ],
       [101.        ],
       [ 99.        ],
       [100.        ],
       [100.        ],
       [100.        ],
       [ 98.        ],
       [ 98.        ],
       [102.        ],
       [104.        ],
       [102.        ],
       [101

In [28]:
X_train.fever.describe()

count     71.000000
mean     100.943662
std        1.984852
min       98.000000
25%       99.500000
50%      101.000000
75%      102.000000
max      104.000000
Name: fever, dtype: float64

## Ordinal encoding

In [38]:
oe = OrdinalEncoder(categories=[["Mild","Strong"]])
X_train_cough=oe.fit_transform(X_train[['cough']])
#also the test data
X_test_cough=oe.fit_transform(X_test[["cough"]])

X_train_cough.shape

(80, 1)

In [40]:
X_test_cough

array([[1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.]])

## OneHotEncoding

In [54]:
ohe=OneHotEncoder(drop="first",sparse_output=False)
#Removes first column from both(gender and city) remaining 4 instead of 6
X_train_gender_city=ohe.fit_transform(X_train[["gender","city"]])
# also for test data
X_test_gender_city=ohe.fit_transform(X_test[["gender","city"]])
X_train_gender_city.shape

(80, 4)

In [55]:
X_test_gender_city

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 1.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# Extracting Age

In [60]:
X_train_age=X_train.drop(columns=["gender",'fever','cough','city']).values
X_test_age=X_test.drop(columns=["gender",'fever','cough','city']).values
X_test_age.shape

(20, 1)

In [61]:
X_test_age

array([[24],
       [10],
       [65],
       [71],
       [34],
       [25],
       [26],
       [65],
       [49],
       [72],
       [51],
       [46],
       [19],
       [70],
       [16],
       [23],
       [83],
       [84],
       [73],
       [ 6]])

In [62]:
X_train_transformed=np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)

In [68]:
X_test_transformed=np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

In [69]:
X_train_transformed.shape

(80, 7)

In [70]:
X_test_transformed

array([[ 24.        , 102.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 10.        , 100.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 65.        ,  98.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 71.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 34.        ,  98.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 25.        ,  99.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 26.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 65.        , 101.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 49.        ,  99.        ,   0.        ,   0.        ,
          0.    

# Using ColumnTransformer

In [71]:
from sklearn.compose import ColumnTransformer

In [85]:
transformer=ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[["Mild","Strong"]]),["cough"]),
    ('tnf3',OneHotEncoder(sparse_output=False,drop="first"),["gender","city"]),
  ],remainder="passthrough")

In [88]:
transformer.fit_transform(X_train).shape

(80, 7)

In [87]:
transformer.transform(X_test).shape

(20, 7)

In [89]:
X_train_transformed=transformer.fit_transform(X_train)

In [91]:
X_test_transformed=transformer.transform(X_test)

In [92]:
X_test_transformed

array([[102.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  24.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  10.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  65.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  71.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  34.        ],
       [ 99.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  25.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  26.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  65.        ],
       [ 99.        ,   1.        ,   0.        ,   0.        ,
          0.    