In [114]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [115]:
df = np.round(pd.read_csv('/content/drive/MyDrive/Datasets/50_Startups.csv')[['R&D Spend','Administration','Marketing Spend','Profit']]/10000)

In [116]:
np.random.seed(9)
df=df.sample(5)
df

R&D Spend  Administration  Marketing Spend  Profit
21        8.0            15.0             30.0    11.0
37        4.0             5.0             20.0     9.0
2        15.0            10.0             41.0    19.0
14       12.0            16.0             26.0    13.0
44        2.0            15.0              3.0     7.0

In [117]:
df=df.iloc[:,0:-1]
df

R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        4.0             5.0             20.0
2        15.0            10.0             41.0
14       12.0            16.0             26.0
44        2.0            15.0              3.0

In [118]:
df.iloc[1,0]=np.nan
df.iloc[3,1]=np.nan
df.iloc[-1,-1]=np.nan

<ipython-input-118-1be612d7084b>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[1,0]=np.nan
<ipython-input-118-1be612d7084b>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[3,1]=np.nan
<ipython-input-118-1be612d7084b>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[-1,-1]=np.nan


In [119]:
df.head()

R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        NaN             5.0             20.0
2        15.0            10.0             41.0
14       12.0             NaN             26.0
44        2.0            15.0              NaN

In [120]:
#Step 1- Impute all missing values with mean of respective col
df0=pd.DataFrame()
df0['R&D Spend']=df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0["Administration"]=df["Administration"].fillna(df["Administration"].mean())
df0["Marketing Spend"]=df["Marketing Spend"].fillna(df["Marketing Spend"].mean())

In [121]:
# 0th Iteration
df0

R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37       9.25            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.25            26.00
44       2.00           15.00            29.25

In [122]:
df1=df0.copy()

df1.iloc[1,0]=np.nan
df1

R&D Spend  Administration  Marketing Spend
21        8.0           15.00            30.00
37        NaN            5.00            20.00
2        15.0           10.00            41.00
14       12.0           11.25            26.00
44        2.0           15.00            29.25

In [123]:
# Use first 3 rows to build a model and use the last for prediction

In [124]:
X=df1.iloc[[0,2,3,4],1:3]
X

Administration  Marketing Spend
21           15.00            30.00
2            10.00            41.00
14           11.25            26.00
44           15.00            29.25

In [125]:
y=df1.iloc[[0,2,3,4],0]
y

21     8.0
2     15.0
14    12.0
44     2.0
Name: R&D Spend, dtype: float64

In [126]:
lr=LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[1,1:].values.reshape(1,2))

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([23.14158651])

In [127]:
df1.iloc[1,0]=23.14

In [128]:
df1

R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.14            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.25            26.00
44       2.00           15.00            29.25

In [129]:
# Remove the col2 imputed value
df1.iloc[3,1]=np.nan
df1

R&D Spend  Administration  Marketing Spend
21       8.00            15.0            30.00
37      23.14             5.0            20.00
2       15.00            10.0            41.00
14      12.00             NaN            26.00
44       2.00            15.0            29.25

In [130]:
X=df1.iloc[[0,1,2,4],[0,2]]
X

R&D Spend  Marketing Spend
21       8.00            30.00
37      23.14            20.00
2       15.00            41.00
44       2.00            29.25

In [131]:
y=df1.iloc[[0,1,2,4],1]
y

21    15.0
37     5.0
2     10.0
44    15.0
Name: Administration, dtype: float64

In [132]:
lr=LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.06331285])

In [133]:
df1.iloc[3,1]=11.06

In [134]:
df1

R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.14            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.06            26.00
44       2.00           15.00            29.25

In [135]:
df1.iloc[-1,-1]=np.nan
df1

R&D Spend  Administration  Marketing Spend
21       8.00           15.00             30.0
37      23.14            5.00             20.0
2       15.00           10.00             41.0
14      12.00           11.06             26.0
44       2.00           15.00              NaN

In [136]:
X=df1.iloc[0:-1,[0,1]]
y = df1.iloc[:4,-1]



In [137]:
lr=LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[-1,[0,1]].values.reshape(1,2))

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([31.56351448])

In [138]:
df1.iloc[-1,-1]=31.5635

In [139]:
#After 1st Iteration
df1

R&D Spend  Administration  Marketing Spend
21       8.00           15.00          30.0000
37      23.14            5.00          20.0000
2       15.00           10.00          41.0000
14      12.00           11.06          26.0000
44       2.00           15.00          31.5635

In [140]:
#Subtract 0th Iteration from 1st Iteration
df1-df0

R&D Spend  Administration  Marketing Spend
21       0.00            0.00           0.0000
37      13.89            0.00           0.0000
2        0.00            0.00           0.0000
14       0.00           -0.19           0.0000
44       0.00            0.00           2.3135

In [141]:
df2=df1.copy()

In [142]:
df2.iloc[1,0]=np.nan
df2

R&D Spend  Administration  Marketing Spend
21        8.0           15.00          30.0000
37        NaN            5.00          20.0000
2        15.0           10.00          41.0000
14       12.0           11.06          26.0000
44        2.0           15.00          31.5635

In [143]:
X=df2.iloc[[0,2,3,4,],1:]
y=df2.iloc[[0,2,3,4],0]
#X
#y
lr=LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[1,1:].values.reshape(1,2))

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([23.78836883])

In [144]:
df2.iloc[1,0]=23.78

In [145]:
#For 2nd val in df2
df2.iloc[3,1]=np.nan
X=df2.iloc[[0,1,2,4,],[0,2]]
y=df2.iloc[[0,1,2,4],1]
#X
#y
lr=LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[3,[0,2]].values.reshape(1,2))

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.22027802])

In [146]:
df2.iloc[3,1]=11.22

In [147]:
df2.iloc[-1,-1]=np.nan
X=df2.iloc[0:-1,[0,1]]
y = df2.iloc[:4,-1]
lr.fit(X,y)
lr.predict(df2.iloc[-1,[0,1]].values.reshape(1,2))


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([38.87979054])

In [148]:
df2.iloc[4,-1]=31.56
df2

R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.78            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.22            26.00
44       2.00           15.00            31.56

In [149]:
df2-df1

R&D Spend  Administration  Marketing Spend
21       0.00            0.00           0.0000
37       0.64            0.00           0.0000
2        0.00            0.00           0.0000
14       0.00            0.16           0.0000
44       0.00            0.00          -0.0035